version: '3.8'
services:
  app:
    container_name: URLs-Shortner-App
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      # - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      APP_PORT: ${APP_PORT}
      DB_HOST_LIVE: ${DB_HOST_LIVE}
      DB_DIALECT: ${DB_DIALECT}
      POOL_MAX: ${POOL_MAX}
      POOL_IDLE: ${POOL_IDLE}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      CALLBACKURL: ${CALLBACKURL}
      LINKEDIN_CLIENT_ID: ${LINKEDIN_CLIENT_ID}
      LINKEDIN_CLIENT_SECRET: ${LINKEDIN_CLIENT_SECRET}
      LINKEDIN_CALLBACKURL: ${LINKEDIN_CALLBACKURL}
      SESSION_SECRET: ${SESSION_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - URLs-Shortner-App
  db:
    container_name: URLs-Shortner-App-Database
    image: postgres
    hostname: localhost
    ports:
      - "5434"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - URLs-Shortner-App

volumes:
  postgres-data:

networks:
  URLs-Shortner-App:
    driver: bridge